id: IF2B72DB5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:58:21+00:00'
last_modified: '2022-06-08T04:44:54.263293+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23817
  title: གསུང་འབུམ། དཀོན་མཆོག་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C946:
      image_group_id: I1KG24475
      title: ''
      total_pages: 740
      order: 1
      base_file: C946.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
