id: P005537
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23817
  title: གསུང་འབུམ། དཀོན་མཆོག་རྒྱལ་མཚན།
  author: ''
  volumes:
    5c6d4877958e45d98a6d794433a0fd1f:
      image_group_id: I1KG24475
      title: ''
      volume_number: 1
      total_pages: 740
